#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_DIR="${ROOT_DIR}/demo_tps_art"

if command -v godot >/dev/null 2>&1; then
  # Running the project requires imported artifacts under .godot/imported/.
  # Those are generated by the editor import pipeline (can be headless).
  if [[ ! -d "${PROJECT_DIR}/.godot/imported" ]]; then
    godot --headless --editor --quit --path "${PROJECT_DIR}"
  fi
  exec godot --path "${PROJECT_DIR}"
fi

GODOT_APP_CANDIDATES=(
  "/Applications/Godot.app"
  "${HOME}/Applications/Godot.app"
)

for app in "${GODOT_APP_CANDIDATES[@]}"; do
  if [[ -d "${app}" ]]; then
    exec open -a "${app}" --args --path "${PROJECT_DIR}"
  fi
done

cat <<'EOF'
找不到可执行的 `godot`，也没发现 `/Applications/Godot.app`。

可选修复方式：
  1) Homebrew 安装（推荐）
     brew install --cask godot
     godot --version
     godot --path demo_tps_art

  2) 手动安装 Godot 4.6.2 后，把 Godot.app 放到 /Applications
     然后再次运行：
     ./demo_tps_art/run.sh
EOF

exit 127

